# Generated by Django 4.2.6 on 2023-10-25 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('post_nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('promotion', models.CharField(max_length=30)),
                ('filiere', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('fichier', models.FileField(upload_to='fichier')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfc.dossier')),
            ],
        ),
        migrations.AddField(
            model_name='dossier',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfc.etudiant'),
        ),
    ]
